name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    # THIS IS THE MAGIC WORD: It tells GitHub to use VM 1 instead of their cloud servers
    runs-on: self-hosted 
    
    steps:
      - name: Download my code
        uses: actions/checkout@v4
        
      - name: Deploy whole directory to VM 2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./src/ hulk@132.1.16.119:/var/www/html/