name: My First Docker Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download my code
        uses: actions/checkout@v4
        
      - name: Build the Docker image
        # This is the exact same build command you use locally!
        run: docker build -t my-python-test .
        
      - name: Run the Docker container
        # This boots up the container to execute the test inside it
        run: docker run my-python-test