name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests: # <--- Notice the name changed here!
    runs-on: ubuntu-latest
    
    steps:
      - name: Download my code
        uses: actions/checkout@v4
        
      - name: Run my Python test
        run: python3 test.py # <--- And the command changed here!